new_vocab = {
    "parish priest": "proboszcz",
    "shipyard": "stocznia",
    "heap, pile; prism": "pryzma",
    "advice": "porada",
    "roe deer": "sarna",
    "to make a fool of somebody": "wystrychnąć kogoś na dudka",
    "to befool": "okpić",
    "to admit to": "przyznać się do",
    "to reveal, disclose": "wyjawić",
    "to aspire to, strive for": "dążyć do",
    "to relocate, reposition, move": "przemieszczać",
    "police inspector": "aspirant",
    "a frame of reference": "układ odniesienia",
    "seemingly, apparently": "pozornie",
    "tether, ring, fetters": "pęto",
    "county": "powiat",
    "adversity, misery, wretchedness": "niedola",
    "the main theme": "wątek główny",
    "weft; motif, theme, thread": "wątek",
    "well (water)": "studnia",
    "pissed off": "wkurzony",
    "best man": "drużba",
    "to bother, to trouble": "fatygować",
    "drowned body": "topielec",
    "to drown; to sink": "topić",
    "howl, wail": "wycie",
    "to tan, sunbathe": "opalić się",
    "altar boy; acolyte": "ministrant",
    "a cold (not feeling good)": "przeziębienie",
    "niech będzie pochwalony": "niech będzie pochwalony",
    "to chase; to pressure, prod": "gonić",
    "income": "przychody",
    "muzzle, snout": "morda",
    "w mordę (shit!)": "w mordę",
    "bait": "przynęta",
    "arrears, backlog": "zaległość",
    "thoughts, reflection": "przemyślenie",
    "doubt, despair": "zwątpienie",
    "proverbial": "przysłowiowy",
    "to water (podlać)": "podlewać",
    "imperfection": "niedoskonałość",
    "to recognize (dostrzec)": "dostrzegać",
    "stuffiness": "duchota",
    "aberrance": "odstępstwo od normy",
    "to train": "szkolić",
    "to gush, jet, burst with": "tryskać",
    "left out, omitted": "pominięty",
    "slumped, slouched": "zgarbiony",
    "capers, advertures, wandering": "perypetia",
    "to establish, form, make": "nawiązać",
    "civil law": "cywilnoprawny",
    "grounds, justification": "uzasadnienie",
    "notice of termination": "wypowiedzenie",
    "average": "przeciętny",
    "reported": "odnotowany",
    "so called": "tak zwany",
    "w Niemczech": "w Niemczech",
    "overtime": "nadgodziny",
    "desirable, desired": "pożądny",
    "rigorous": "rygorystyczny",
    "overpowering, overwhelming": "przytłaczający",
    "to guess": "zgadnąć",
    "pay raise": "podwyżka",
    "to make an observation": "poczynić spostrzeżenie",
    "high tide; surge": "przypływ",
    "established": "założony",
    "to use up, spend, wear away": "zużywać",
    "disperse, split; distract": "rozpraszać",
    "lossing weight": "utrata wagi",
    "New Year's resolution": "noworoczne postanowienie",
    "related, similar": "pokrewny",
    "humiliated, abased": "upokorzony",
    "yarn": "przędza",
    "appointed, stated, set down": "wyznaczony",
    "stimulus; incentive, spur": "bodziec",
    "instrument, agent, apparatus": "przyrząd",
    "activist": "działacz",
    "plough": "płog",
    "to draw water": "czerpać wodę",
    "passive": "bierny",
    "defeat; failure": "porażka",
    "challenge": "wyzwanie",
    "repetition": "powtarzalność",
    "to assimilate": "przyswoić",
    "outdated, antiquated": "przestarzały",
    "to make off, flee": "umknąć",
    "to coax, urge": "namawiać",
    "to work out, guess": "domyślić się",
    "perseverance, tenacity": "wytrwałość",
    "to enhance, bolster": "wzmacniać",
    "frozen ground; lump": "gruda",
    "bubble gum": "balonówa",
    "prank": "psikus",
    "failed": "niezdany",
    "to knock, rap; to knock sb off": "stuknąć",
    "to be grounded, punished": "mieć szlaban",
    "brain teaser, puzzle": "łamigłówka",
    "store, reserves": "zasób",
    "discount": "zniżka",
    "trump card, cheif asset": "atut",
    "maintenance": "utrzymanie",
    "comely, good-looking": "urodziwy",
    "located": "położony",
    "bullet points": "wypunktowanie",
    "undertaking, entering into, take on": "podjęcie",
    "well rested": "wypoczęty",
    "taciturn, curt": "mrukliwy",
    "life, life history; CV": "życiorys",
    "radioactivity": "promieniotwórczość",
    "distinguished": "zasłużony",
    "creator, author": "twórca",
    "close by, right by": "tuż",
    "włosy na ciele człowieka lub zwierzęcia": "owłosienie",
    "coming into being": "postawnie",
    "assailant, attacker; (soccer) forward": "napastnik",
    "decoration, award": "odznaczenie",
    "conflict; game, match": "rozgrywka",
    "to keep under surveillance": "inwigilować",
    "president, chairperson": "przewodniczący",
    "abolishment, overthrow, confutation": "obalenie",
    "to get, to reach": "dotrzeć",
    "omówienie": "omówienie",
    "oversensitity, touchiness, irritability": "drażliwość",
    "medical examination; study; research": "badanie",
    "ognisty": "ognisty",
    "trade union (adj)": "związkowy",
    "convoluted": "zawiły",
    "tuberculosis": "gruźlica",
    "examination, inspection": "oględziny",
    "buried": "pochowany",
    "to encircle, enclose": "obiegać",
    "office worker, clerk; official": "urzędnik",
    "orientation": "zapozanie",
    "to familiarize oneself with": "osłuchać się z czymś",
    "to attribute, assign": "przypisać",
    "udostępniony": "udostępniony",
    "SEO, brand positioning": "pozycjonowanie",
    "azure blue": "lazurowy",
    "development": "rozwój",
    "dilemea": "dylemat",
    "well-matched, suited": "dobrany",
    "wrong, improper, abnormal": "nieprawidłowy",
    "to obtain, acquire": "zdobyć",
    "when the need arises": "gdy nadejdzie taka potrzeba",
    "Ethical dilemmas arise": "pojawiają się dylematy etyczne",
    "progress": "postęp",
    "economy": "gospodarka",
    "perception": "postrzeganie",
    "to spill": "rozlać",
    "tight-fitting; cramped": "ciasny",
    "dalszy widok np. obrazu, dalszy plan; okoliczności, sytuacja, w której rozgrywają się jakieś wydarzenia": "tło",
    "in the background": "w tle",
    "mała furta, jednoskrzydłowe wejście, np. na ogrodzony teren": "furtka",
    "faded": "wyblakły",
    "slide, window": "przeźrocze",
    "to flex, to tighten": "prężyć",
    "to abandon": "porzucić",
    "to linger; to delay": "zwlekać",
    "to glue together": "posklejać",
    "spare change": "drobniaki",
    "first verse": "pierwsza zwrotka",
    "alike": "jednaki",
    "embrace": "objęcie",
    "solution": "rozwiązanie",
    "reakcja na pytanie; rozwiązanie zadania, zagadki, łamigłówki": "odpowiedź",
    "statement; expression; coś, co zostało powiedziane, wypowiedziane lub napisane": "wypowiedź",
    "przyrząd służący do mechanicznego odtwarzania liter, kształtów lub całych rysunków; forma, wzór, według których wyrabia się seryjnie przedmioty": "szablon",
}

vocab = {
    "commonplace": "utarty",
    "behavior, conduct": "postępowanie",
    "reference, mention": "wzmianka",
    "medical examination; study; research": "badanie",
    "practice; rut; routine": "rutyna",
    "to give rise to, beget, engender": "zrodzić",
    "to be born, to arise": "zrodzić się",
    "training": "szkolenie",
    "okpić, wprowadzić kogoś w błąd, wystrychnąć kogoś na dudka, oszukać": "zrobić kogoś na szaro",
    "attitude": "nastawienie",
    "trivial, trite": "błahy",
    "overtone": "wydźwięk",
    "mycelia": "grzybnie",
    "to examine, observe": "przyjrzeć",
    "to shake, upset, undermine": "zachwiać",
    "unwavering, undeterred": "niezachwiany",
    "to appreciate, hold in high esteem": "doceniać",
    "a mild climat": "umiarkowany klimat",
    "a true blessing": "prawdziwie błogosławieństwo",
    "to take place, be held": "odbyć się",
    "achievement, success": "osiągnięcie",
    "violin": "skrzypce",
    "output, ouevre, work": "dorobek",
    "to get, obtain": "uzyskać",
    "overwhelmed": "przytłoczony",
    "otherwise": "skądinąd",
    "mechanizm służący do wykonywania określonych zadań / czynności": "urządzenie",
    "wyjawić coś ważnego; przyznać się do czegoś": "wyznać",
    "doświadczenie w wykonywaniu czegoś": "wprawa",
    "przyzwyczajać, zaznajamiać z czymś; przyzwyczajać dzikie zwierzę do przebywania wśród ludzi; obłaskawiać": "oswajać",
    "dążyć do uzyskania czegoś, próbować coś uzyskać; to seek, apply for": "ubiegać się o",
    #
    "zdawać egzamin": "zdawać egzamin",
    "w zależności od": "w zależności od",
    "przechodzić, przejeżdżać obok kogoś, czegoś; (o czasie, zjawiskach): stawać się przeszłością, przemijać, upływać, kończyć się; ( aspekt dokonany od mijać)": "minąć",
    "przestać żyć; skonać": "umrzeć",
    "stan zagrożenia": "niebezpieczeństwo",
    "stan braku zagrożeń": "bezpieczeństwo",
    "impreza sportowa podczas której zawodnicy rywalizują ze sobą; rywalizacja": "zawody",
    "przeprowadzać": "przeprowadzać wywiad",
    "dostać białej gorączki": "dostać białej gorączki",
    "wypowiedź zapewniająca kogoś o zrobieniu czegoś w przyszłości": "obietnica",
    "obiecywać złote góry": "obiecywać złote góry",
    "stan psychiczny lub fizyczny odczuwany bezpośrednio przez daną osobę": "samopoczucie",
    "pryzma śniegu": "zaspa",
    "termin ogólny oznaczający ogół aktywności mózgu ludzkiego, przede wszystkim takich, których posiadania człowiek jest świadomy": "umysł",
    "ważny ludzki zmysł, którego głównym zadaniem jest komunikowanie się z innymi ludźmi": "zmysł słuchu",
    "węch; jeden z dwóch – obok smaku – zmysłów chemicznych": "zmysł powonienia",
    "znaczący dokładnie to, co wyrażają słowa, bez drugiego znaczenia": "dosłowny",
    "grać lub śpiewać nieczysto": "fałszować",
    "[jęz. liter.] taki, którego używa się na co dzień, w zwykłej rozmowie; zwykły, codzienny, pospolity, powszechny, popularny": "potoczny",
    "chodzić spać bardzo wcześnie": "chodzić spać z kurami",
    "taki, jak należy; odpowiedni, stosowny, adekwatny": "należyty",
    "podobizna, portret; dowód, świadectwo czegoś": "wizerunek",
    "marna zapłata": "psie pieniądze",
    "pogoda brzydka": "pogoda pod psem",
    "niechętnie oddający swoje dobra, pieniądze; bardzo mały, o małej objętości": "skąpy",
    "dofinansowanie do wypoczynku z funduszu socjalnego": "wczasy pod gruszą",
    "podjęcie jakiegoś działania; rozpoczęcie stosowania czegoś w praktyce; (implementation)": "wdrożenie",
    """stan psychiczny charakteryzujący się przede wszystkim stałym, wewnętrznym przymusem wykonywania pracy lub innych czynności
    z nią związanychworkaholism""": "pracoholizm",
    "ilość wykonanych usług lub wytworzonych produktów przez danego pracownika w jednostce czasu": "wydajność pracy",
    "przemieszczać coś przy pomocy jakiegoś pojazdu": "wozić",
    "sprawiać, że coś nie znajduje się już w miejscu, w którym było; kasować dane z dysku itp.": "usuwać",
    "marzyć o niebieskich migdałach": "marzyć o niebieskich migdałach",
    "ten, który zwyciężył, wygrał": "zwycięzca",
    "szósty miesiąc w roku (od słowa czerw oznaczającego robaka)": "czerwiec",
    "ósmy miesiąc w roku": "sierpień",
    "dziewiąty miesiąc w roku": "wrzesień",
    "regeneracja i odzyskiwanie sił w czasie wolnym od pracy": "wypoczynek",
    "o wilku mowa, a wilk tu": "o wilku mowa, a wilk tu",
    "reakcja organizmu na presję, której źródłem jest praca": "wypalenie zawodowe",
    "być skąpy": "mieć węża w kieszeni",
    "zorganizowany wielodniowy wypoczynek poza miejscem zamieszkania": "wczasy",
    "gatunek niejadowitego węża z rodziny połozowatych": "zaskroniec",
    "jedyny jadowity dziko występujący wąż w Polsce": "żmija",
    "dzieło literackie lub muzyczne": "utwór",
    "dzieła; prace tworzone przez kogoś, ogół dorobku twórczego; dorobek artystyczny; 'biesiady'; akt": "twórczość",
    "możliwy do zniesienia, akceptowalny, taki, z którym można wytrzymać": "znośny",
    "szkola wyższa": "uczelnia",
    "owłosienie w dolnej części twarzy": "zarost",
    "szczegół lub informacja budząca zainteresowanie": "ciekawostka",
    "pensja, wypłata; rekompensata (od wynagrodzić)": "wynagrodzenie",
    "(książk.) stan ogromnego podniecenia, gotowość do działania; entuzjazm, ferwor, pasja": "zapał",
    "nie do uniknięcia, na pewno, koniecznie; inevitable": "niechybny",
    "(psych.) chroniczna potrzeba dostarczania określonych, na ogół szkodliwych bodźców do organizmu człowieka, zwykle sprzeczna z jego wolą i intelektem": "uzależnienie",
    "osoba pochodząca z innego kraju": "obcokrajowiec",
    "udzielać komuś sakramentu chrztu": "chrzcić",
    "usuwać zarost lub owłosienie, tnąc je tuż przy skórze": "golić",
    "iść za kimś lub za czymś po jego śladach – tropach, zapachu": "tropić",
    "dotyczący dziewczyny, taki, jak u dziewczyny/dziewczynki": "dziewczęcy",
    "człowiek pochodzący z tego samego narodu": "rodak",
    "praw. urz. związek prawny osoby fizycznej z jakimś państwem, który daje jej określone prawa i obowiązki": "obywatelstwo",
    "osoba lub przedsiębiorstwo zatrudniające pracowników": "pracodawca",
    "inform. narzędzie służące do wyszukiwania informacji w sieci www": "wyszukiwarka",
    "taki, który właśnie, obecnie trwa; płynący, posuwający się naprzód": "bieżący",
    "ekon. ilość dóbr i usług, którą konsumenci są w stanie nabyć po określonej cenie i w określonym czasie": "popyt",
    "ekon. dostępność, oferta towarów na sprzedaż; t. ilość danego towaru znajdująca się na rynku": "podaż",
    "małe, ciasne pomieszczenie": "klitka",
    "żona ojca, ale nie matka": "macocha",
    "tak, żeby nie zwrócić niczyjej uwagi": "ukradkiem",
    "gęste skupienie roślin, zwłaszcza krzewów i drzew": "gęstwina",
    "przy okazji, od niechcenia, ubocznie": "mimochodem",
    "praca wykonywana całkowicie lub częściowo w miejscu wskazanym przez pracownika": "praca zdalna",
    "pracownicy w danej firmie łączą pracę w biurze i home office": "praca hybryda",
    "osoba, która używa czegoś, użytkuje coś": "użytkownik",
    "mówić mimochodem": "wspomnieć",
    "być niemuzykalny": "słoń na ucho nadepnął",
    "zwymiotować": "puścić pawia",
    "osoba, której umiejętności są zaskakujące i dotychczas nieznane": "czarny koń",
    "jedzmy i pijmy; boć jutro pomrzemy": "jedzmy i pijmy; boć jutro pomrzemy",
    "ogół technik, procesów i praktyk stosowanych w celu ochrony sieci informatycznych, urządzeń, programów i danych przed atakami, uszkodzeniami lub nieautoryzowanym dostępem": "cyberbezpieczeństwo",
    "biegłość w wykonywaniu czegoś, nabyta w wyniku ćwiczeń, powtarzania jakiejś czynności": "wprawa",
    "ciągnąć nić, przędzę; planować, zamierzać": "snuć",
    "otrzymanie czegoś od kogoś w zamian za coś innego": "wymiana",
    "wyrażać coś dźwiękowo, słownie; aspekt dokonany od wymawiać": "wymówić",
}

